### ISSUE TITLE
no submitHandler callback

### ISSUE THREAD

**Issue by skyl** [alex/django-ajax-validation#1]
I would like a place to insert a callback for when the form is valid and before it submits.

like the submitHandler callback here:
http://docs.jquery.com/Plugins/Validation/validate#toptions

The invalid Handler is pretty nice too but I think that is approximately what your callback does.

**Comment by tmc** [comment]
I added a 'success' callback in my branch, renaming to submitHandler now.

**Comment by alex** [comment]
Closed by 47ca14610b736598d0399255ba5ad11df1a4a974.  Added support for a submitHandler callback.  Thanks to Travis Cline
