### ISSUE TITLE
Form constructor callback doesn't allow to edit 'data' item

### ISSUE THREAD

**Issue by epper** [alex/django-ajax-validation#2]
In views.validate you have:
    def validate(request, _args, *_kwargs):
      form_class = kwargs.pop('form_class')
      extra_args_func = kwargs.pop('callback', lambda request, _args, *_kwargs: {})
      kwargs = extra_args_func(request, _args, *_kwargs)
      kwargs['data'] = request.POST
      form = form_class(**kwargs)

I think it would be better to enable the callback function to change also the 'data' parameter passed to the form constructor.
A common use case is a Comment Applcation where for an anonymous user you have post fields with its data (nick, email, url) while for authenticated users you don't have that fields in the POST request and a callback function could simply specify them!
(This is the way the Comment Application bundled with django works)

So, I suggest to convert that code to something like that:
    def validate(request, _args, *_kwargs):
      form_class = kwargs.pop('form_class')
      extra_args_func = kwargs.pop('callback', lambda request, _args, *_kwargs: {'data':request.POST})
      kwargs = extra_args_func(request, _args, *_kwargs)
      form = form_class(**kwargs)

**Comment by alex** [comment]
Closed by 271f90327a4b20d25c95fb25378cc769f168e897.  It is now possible to override the data parameter to the Form's constructor
