### ISSUE TITLE
Not always showing errors in the right form

### ISSUE THREAD

**Issue by epper** [alex/django-ajax-validation#3]
In the jQuery plugin, fields to attach errors are searched this way:
    $('#' + key)....
The problem is that can happen to have more than one form in one page and that the two forms have a field with the same name (which results in two fields with same id in the HTML source).
This shouldn't happen since two elements cannot have the same id in HTML, but this is the way it works for now with django.

So, to assure that the errors are shown next to the right field, I think fields should be serached this way instead:
    form.find('#' + key)...

Thanks for your great plugin ;)

**Comment by epper** [comment]
Am I wrong?

**Comment by Arvi3d** [comment]
wrong. because W3C standart explictly defines that id field must be unique.
About django forms...  use prefix.

**Comment by alex** [comment]
I agree with Avri3d, you're Id's should be unique.
